# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain1-ingress-path
  namespace: sample-domain1-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
      - path: /domain1(.+)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sample-domain1-cluster-cluster-1
            port:
              number: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: domain2-ingress-path
  namespace: sample-domain2-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
      - path: /domain2(.+)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sample-domain2-cluster-cluster-1
            port:
              number: 8001